spring.application.name=productcatalog
fakeStore.url=https://fakestoreapi.com/products/
server.error.include-stacktrace=never

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.profiles.active=rds

#spring.security.oauth2.authorizationserver.issuer=http://localhost:8081
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081

#spring.datasource.hikari.connectionTimeout=20000
#spring.datasource.hikari.maximumPoolSize=5
